### ISSUE TITLE
Collaboration request

### ISSUE THREAD

**Issue by Akul2010** [gab-luz/ameli-ai#2]
Hey hi, I am working on a similar project and would like to ask whether you want to help out. I can't pay, sorry, but I would be willing to work in my free time. Github here - https://github.com/Akul-AI

**Comment by gab-luz** [comment]
> Hey hi, I am working on a similar project and would like to ask whether you want to help out. I can't pay, sorry, but I would be willing to work in my free time. Github here - https://github.com/Akul-AI

Oh snap. I didn't see your message. Perhaps we can make a colab, yes, but we might have totally different visions of the same project so I think it would be good if you choose a specific part of your project so that I can work on. Also, I'm a part time designer so I might have some ideas. Working on a free time is what I do since web development or development in general is not my main job so no pay is okay. My goal is mainly learn more and more. We can learn and earn money in other projects with what we learn, do you agree?
Reach me at agabrielads @ live dot com (live.com) so you can talk to me exactly where you need me and I'll see if I can help you.
Also, I'd like to talk to a real person if you don't mind haha.
